import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import { Header } from "./components/Header";
const roboto = Roboto({ subsets: ['latin'], weight: '400', display: 'swap' })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}


export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={roboto.className}>
				<div className="container">
					<Header />
					{children}
				</div>

			</body>
		</html>
	)
}
